routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');

//Admin routes
Route::group(['middleware' => ['auth:admin'], 'prefix' => 'admin'], function(){

	Route::get('/', 'AdminsController@index')->name('admin.index');
	//Get users
	Route::get('user', 'AdminsController@getUsers')->name('admin.user.index');
	//Get Items
	Route::get('item', 'AdminsController@getItems')->name('admin.item.index');
	//Get checklists
	Route::get('checklist', 'AdminsController@getChecklists')->name('admin.checklist.index');

	Route::get('checklist/{id}/show', 'AdminsController@getChecklistById')->name('admin.checklist.show');

	Route::get('user/{id}/task', 'AdminsController@getUserTasks')->name('admin.user.task.index');
	

});

Route::group(['middleware' => ['roles:owner|manager']], function(){
	//Item resource controller
	Route::resource('item', 'ItemsController')->except(['show', 'destroy']);

	//Checklist resource controller
	Route::resource('checklist', 'ChecklistsController')->except([ 'destroy']);

	//Checklist resource controller
	Route::post('pre/checklist/{id}/use_again', 'ChecklistsController@useAgainCheclistById')->name('checklist.use_again');
	//Check task route
	Route::get('check/task', 'TasksController@checkTasks')->name('check.task.index');

});

Route::group(['middleware' => ['roles:owner|manager|cleaning|renter']], function(){
	//task route
	Route::get('task', 'TasksController@index')->name('task.index');
	Route::get('task/create/checklist/{checklist_id}', 'TasksController@create')->name('task.create');
	Route::post('task/store', 'TasksController@store')->name('task.store');
});

resources/views/admin/checklist_list.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- DATA TABLE -->
            <h3 class="title-5 m-b-35">All Checklist</h3>
            <div class="table-data__tool">
                <div class="table-data__tool-right pull right">
                    <a class="au-btn au-btn-icon au-btn--green au-btn--small btn btn-sm btn-success" href="{{route('checklist.create')}}">
                        <i class="zmdi zmdi-plus"></i>add checklist</a>
                </div>
            </div>
            <div class="table-responsive table-responsive-data2">
                <table class="table table-data2">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($data->count())
                            @foreach($data as $key => $checklist)
                                <tr class="tr-shadow">
                                    <td>
                                        {{ ++ $key}}
                                    </td>
                                    <td>{{$checklist->name}}</td>
                                    <td>{{$checklist->start_date}}</td>
                                    <td>{{$checklist->end_date}}</td>
                                    <td>
                                        <div class="table-data-feature">
                                            <a class="item btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Edit" href="{{route('admin.checklist.show', $checklist->id)}}">
                                                <i class="zmdi zmdi-edit"></i>Preview
                                            </a>
                                            |
                                            {{-- {{Form::open(['route' => ['checklist.use_again', $checklist->id], 'method' => 'POST', 'class' => 'd-inline'])}}
                                                {{Form::hidden('checklist_id', $checklist->id)}}
                                                <button type="submit" class="btn-sm btn btn-success" onclick=" return confirm('Are you sure?')">Use it in next check list</button>
                                            {{Form::close()}} --}}
                                        </div>
                                    </td>
                                </tr>
                                <tr class="spacer"></tr>
                            @endforeach
                        @else
                            No data
                        @endif
                    </tbody>
                </table>
            </div>
            <!-- END DATA TABLE -->
        </div>
    </div>
@endsection

resources/views/admin/checklist_show.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Checklist</strong> show
            </div>

            @if ($errors->any())
                <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
                    <span class="badge badge-pill badge-danger"></span>
                    {{ implode('', $errors->all(':message')) }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif          
            <div class="card-body card-block">
                     <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="name" class=" form-control-label">Checklist Name*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <p>{{$checklist->name}}</p>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="title" class=" form-control-label">Start Date*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <p>{{$checklist->start_date}}</p>                            
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="title" class=" form-control-label">End Date*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <p>{{$checklist->end_date}}</p>                            
                            
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="role_id" class=" form-control-label">For Role</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <p>{{implode(', ', $checklist->roles->pluck('name')->toArray())}}</p>
                            
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="select" class=" form-control-label">Items</label>
                        </div>
                        <div class="col-12 col-md-9">
                                <div class="form-check">
                                    <div class="checkbox">
                                        <label for="checkbox1" class="form-check-label ">
                                            {{implode(', ', $checklist->items->pluck('name')->toArray())}}
                                        </label>
                                    </div>
                               
                                </div>
                            
                        </div>
                    </div>                    
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
@endsection

resources/views/admin/home.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/item_list.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- DATA TABLE -->
            <h3 class="title-5 m-b-35">All Items</h3>
            <div class="table-data__tool">
                <div class="table-data__tool-right pull right">
                    <a class="au-btn au-btn-icon au-btn--green au-btn--small btn btn-sm btn-success" href="{{route('item.create')}}">
                        <i class="zmdi zmdi-plus"></i>add item</a>
                </div>
            </div>
            <div class="table-responsive table-responsive-data2">
                <table class="table table-data2">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>name</th>
                            <th>created at</th>
                            {{-- <th>Action</th> --}}
                        </tr>
                    </thead>
                    <tbody>
                        @if($data->count())
                            @foreach($data as $key => $item)
                                <tr class="tr-shadow">
                                    <td>
                                        {{ ++ $key}}
                                    </td>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->created_at}}</td>
                                    {{-- <td>
                                        <div class="table-data-feature">
                                            <a class="item btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Edit" href="{{route('item.edit', $item->id)}}">
                                                <i class="zmdi zmdi-edit"></i>Edit
                                            </a>
                                        </div>
                                    </td> --}}
                                </tr>
                                <tr class="spacer"></tr>
                            @endforeach
                        @else
                            No data
                        @endif
                    </tbody>
                </table>
            </div>
            <!-- END DATA TABLE -->
        </div>
    </div>
@endsection