routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');

//Admin routes
Route::group(['middleware' => ['auth:admin'], 'prefix' => 'admin'], function(){

	Route::get('/', 'AdminsController@index')->name('admin.index');
	//Get users
	Route::get('user', 'AdminsController@getUsers')->name('admin.user.index');
	//Get Items
	Route::get('item', 'AdminsController@getItems')->name('admin.item.index');
	//Get checklists
	Route::get('checklist', 'AdminsController@getChecklists')->name('admin.checklist.index');

	Route::get('checklist/{id}/show', 'AdminsController@getChecklistById')->name('admin.checklist.show');

	Route::get('user/{id}/task', 'AdminsController@getUserTasks')->name('admin.user.task.index');
	

});

Route::group(['middleware' => ['roles:owner|manager']], function(){
	//Item resource controller
	Route::resource('item', 'ItemsController')->except(['show', 'destroy']);

	//Checklist resource controller
	Route::resource('checklist', 'ChecklistsController')->except([ 'destroy']);

	//Checklist resource controller
	Route::post('pre/checklist/{id}/use_again', 'ChecklistsController@useAgainCheclistById')->name('checklist.use_again');
	//Check task route
	Route::get('check/task', 'TasksController@checkTasks')->name('check.task.index');

});

Route::group(['middleware' => ['roles:owner|manager|cleaning|renter']], function(){
	//task route
	Route::get('task', 'TasksController@index')->name('task.index');
	Route::get('task/create/checklist/{checklist_id}', 'TasksController@create')->name('task.create');
	Route::post('task/store', 'TasksController@store')->name('task.store');
});

app/Models/Checklist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Checklist extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'start_date', 'end_date', 'for_renter',
    ];

    //Many to Many Relation with items
    public function items(){

    	return $this->belongsToMany('App\Models\Item');
    }

    //Has only one relation with task
    public function task(){

        return $this->hasOne('App\Models\Task');
    }

    public function roles(){

        return $this->belongsToMany('App\Models\Role');
    }

}

app/Http/Controllers/ChecklistsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Checklist;
use App\Models\Item;
use App\Models\Role;
use Carbon\Carbon;
use Auth;

class ChecklistsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $for_renter = false;//assign a boolean false
        // if(Auth::user()->hasRole('renter'))//check if role is renter
        //     $for_renter = true;
        $data = Checklist::get(); //get all checklist

        return view('checklists.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $items = Item::get();//Get all items
        $query = Role::whereNotNull('id');
        if(!Auth::user()->hasRole('owner'))//Cjeck if the logged in user is owner
            $query->where('name', '!=', 'owner');
        // if(Auth::user()->hasRole('renter'))//Check if the current user is renter
        //     $query->where('name', '=', 'renter');
        // else
            // $query->where('name', '!=', 'renter');
        $roles = $query->get();//Get all roles

        return view('checklists.create', compact('items', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $for_renter = false;//assign a boolean false
        // if(Auth::user()->hasRole('renter'))//check if role is renter
        //     $for_renter = true;

        $checklist = ['name' => $request->name, 'start_date' => $request->start_date, 'end_date' => $request->end_date,];
        // dd($checklist);
        $data = Checklist::create($checklist);//store checklist

        $data->items()->attach($request->item_id);//store checklist item to pivot
        $data->roles()->attach($request->role_id);//assign checklist to role

        return redirect()->route('checklist.index')->with('success', 'Item created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function show($id)
    // {
    //     //
    // }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $items = Item::get();
        $checklist = Checklist::find($id);
        $query = Role::whereNotNull('id');
        if(!Auth::user()->hasRole('owner'))//Cjeck if the logged in user is owner
            $query->where('name', '!=', 'owner');
        // if(Auth::user()->hasRole('renter'))//Check if the current user is renter
        //     $query->where('name', '=', 'renter');
        // else
        //     $query->where('name', '!=', 'renter');

        $roles = $query->get();//Get all roles

        return view('checklists.edit', compact('items', 'checklist', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $for_renter = false;//assign a boolean false
        // if(Auth::user()->hasRole('renter'))//check if role is renter
        //     $for_renter = true;

        $data = Checklist::find($id);//find checklist by id
        $data->name = $request->name;
        $data->start_date = $request->start_date;
        $data->end_date = $request->end_date;
        // $data->for_renter = $for_renter;
        $data->save();
        // dd($data->items);

        $data->items()->sync($request->item_id);//update checklist item to pivot
        $data->roles()->sync($request->role_id);//assign checklist to role

        return redirect()->route('checklist.index')->with('success', 'Item updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function destroy($id)
    // {
    //     //
    // }
    
    /**
     *  [useAgainCheclistById description]
     *
     *  @method useAgainCheclistById
     *
     *  @param  Request $request [description]
     *  @param  [type] $id [description]
     *
     *  @return [type] [description]
     */
    
    public function useAgainCheclistById(Request $request, $id){

        $items = [];
        $roles = [];
        $data = Checklist::with('roles')->with('items')->find($id);// get the checklist
        $start_date = Carbon::createFromFormat('Y-m-d', $data->start_date);
        $end_date = Carbon::createFromFormat('Y-m-d', $data->end_date);
        $diff = $end_date->diffInDays($start_date);//calculate the days between startdate and enddate
        foreach ($data->items as $item) {

            $items[] = $item->id;//add checklist items in an array
        }
        foreach ($data->roles as $role) {

            $roles[] = $role->id;//add checklist role in an array
        }
        // dd($roles);
        //create checklist
        $checklist = Checklist::create(['name' => $data->name, 'start_date' => date('Y-m-d', strtotime($data['end_date']. ' + 1 days')), 'end_date' => date('Y-m-d', strtotime($data['end_date']. ' + ' . $diff . ' days')),]);
        $checklist->items()->attach($items);
        $checklist->roles()->attach($roles);//assign checklist to role

        return redirect()->back()->with('success', 'Checklist added');
    } 
    
}

resources/views/checklists/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Checklist</strong> Add Items
            </div>

            @if ($errors->any())
                <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
                    <span class="badge badge-pill badge-danger"></span>
                    {{ implode('', $errors->all(':message')) }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif          
            <div class="card-body card-block">
                {{Form::open(['route' => 'checklist.store', 'class' => 'form-horizontal', 'method' => 'POST'])}}
                     <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="name" class=" form-control-label">Checklist Name*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text" id="text-input" name="name" placeholder="Checklist Name" class="form-control" required>
                            <small class="form-text text-muted">Enter the Checklist name</small>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="title" class=" form-control-label">Start Date*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="date" name="start_date" placeholder="Start Date" class="form-control datetimepicker-input" id="datepicker" required>
                            
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="title" class=" form-control-label">End Date*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="date" name="end_date" placeholder="End Date" class="form-control datetimepicker-input" id="datepicker" required>
                            
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="role_id" class=" form-control-label">Select Role*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <select name="role_id[]" class="custom-select selectpicker" multiple required>
                              @foreach($roles as $role)
                                <option value="{{$role->id}}">{{$role->name}}</option>
                              @endforeach
                            </select>
                            
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="select" class=" form-control-label">Select Items</label>
                        </div>
                        <div class="col-12 col-md-9">
                            @foreach($items as $item)
                                <div class="form-check">
                                    <div class="checkbox">
                                        <label for="checkbox1" class="form-check-label ">
                                        {{ Form::checkbox('item_id[]', $item->id, null, ['class' => 'form-check-input', 'id' => 'checkbox1']) }} {{$item->name}}
                                        </label>
                                    </div>
                               
                                </div>
                            @endforeach
                            
                        </div>
                    </div>                    

                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                {{Form::close()}}
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
@endsection

resources/views/checklists/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Checklist</strong> Add Items
            </div>

            @if ($errors->any())
                <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
                    <span class="badge badge-pill badge-danger"></span>
                    {{ implode('', $errors->all(':message')) }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif          
            <div class="card-body card-block">
                {{Form::model($checklist, ['route' => ['checklist.update', $checklist->id], 'class' => 'form-horizontal', 'method' => 'PUT'])}}
                     <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="name" class=" form-control-label">Checklist Name*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text" id="text-input" name="name" placeholder="Checklist Name" class="form-control" value="{{$checklist->name}}" required>
                            <small class="form-text text-muted">Enter the Checklist name</small>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="title" class=" form-control-label">Start Date*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="date" name="start_date" placeholder="Start Date" class="form-control datetimepicker-input" id="datepicker" value="{{$checklist->start_date}}" required>
                            
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="title" class=" form-control-label">End Date*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="date" name="end_date" placeholder="End Date" class="form-control datetimepicker-input" id="datepicker" value="{{$checklist->end_date}}" required>
                            
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="role_id" class=" form-control-label">Select Role*</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <select name="role_id[]" class="custom-select selectpicker" multiple required>
                              @foreach($roles as $role)
                                <option value="{{$role->id}}" {{in_array($role->id, $checklist->roles->pluck('id')->toArray()) ? 'selected' : ''}}>{{$role->name}}</option>
                              @endforeach
                            </select>
                            
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="select" class=" form-control-label">Select Items</label>
                        </div>
                        <div class="col-12 col-md-9">
                            @foreach($items as $item)
                                <div class="form-check">
                                    <div class="checkbox">
                                        <label for="checkbox1" class="form-check-label ">
                                        {{ Form::checkbox('item_id[]', $item->id, in_array($item->id, $checklist->items->pluck('id')->toArray()), ['class' => 'form-check-input', 'id' => 'checkbox1']) }} {{$item->name}}
                                        </label>
                                    </div>
                               
                                </div>
                            @endforeach
                            
                        </div>
                    </div>                    

                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Update
                    </button>
                {{Form::close()}}
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
@endsection

resources/views/checklists/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- DATA TABLE -->
            <h3 class="title-5 m-b-35">All Checklist</h3>
            <div class="table-data__tool">
                <div class="table-data__tool-right pull right">
                    <a class="au-btn au-btn-icon au-btn--green au-btn--small btn btn-sm btn-success" href="{{route('checklist.create')}}">
                        <i class="zmdi zmdi-plus"></i>add checklist</a>
                </div>
            </div>
            <div class="table-responsive table-responsive-data2">
                <table class="table table-data2">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($data->count())
                            @foreach($data as $key => $checklist)
                                <tr class="tr-shadow">
                                    <td>
                                        {{ ++ $key}}
                                    </td>
                                    <td>{{$checklist->name}}</td>
                                    <td>{{$checklist->start_date}}</td>
                                    <td>{{$checklist->end_date}}</td>
                                    <td>
                                        <div class="table-data-feature">
                                            <a class="item btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Edit" href="{{route('checklist.edit', $checklist->id)}}">
                                                <i class="zmdi zmdi-edit"></i>Preview
                                            </a>
                                            |
                                            {{Form::open(['route' => ['checklist.use_again', $checklist->id], 'method' => 'POST', 'class' => 'd-inline'])}}
                                                {{Form::hidden('checklist_id', $checklist->id)}}
                                                <button type="submit" class="btn-sm btn btn-success" onclick=" return confirm('Are you sure?')">Use it in next check list</button>
                                            {{Form::close()}}
                                        </div>
                                    </td>
                                </tr>
                                <tr class="spacer"></tr>
                            @endforeach
                        @else
                            No data
                        @endif
                    </tbody>
                </table>
            </div>
            <!-- END DATA TABLE -->
        </div>
    </div>
@endsection